name: Kops Github Action
description: Setup Kops and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  kops-version:
    default: 1.18.0
    description: Set Kops version
    required: false
  kubeconfig:
    default: ''
    description: Kubernetes cluster configuration file
    required: false
  command:
    description: Kops command to execute
    required: true
  state-store:
    description: Kops state store
    required: true
  cluster-name:
    description: Kops cluster name
    required: true
outputs: {}
runs:
  using: node12
  main: index.js
